import { publicProcedure } from '@/configs/trpc/settings';
import { LANGUAGE } from '@/constants';
import { createClient } from '@/database/supabase/server';
import type { Message } from '@/database/indexed';
import { sendMessageSchema } from '@/schema/trpc/chat';
import { assertEnum, CustomError } from '@/utils';
import { onlyClientRequest } from '@/utils/server';
import { translate } from '@/utils/server/node';

export const sendMessage = publicProcedure
  .input(sendMessageSchema)
  .mutation(
    async ({ input: { message, receiverId, receiverLanguage, roomId }, ctx }) => {
      onlyClientRequest(ctx);

      const supabase = await createClient();
      const { data: { user }, error: authError } = await supabase.auth.getUser();
      
      if (authError || !user) {
        throw new CustomError({ code: 'UNAUTHORIZED' });
      }

      const senderId = user.id;

      // Check if user is participant of the room
      const { data: participant, error: participantError } = await supabase
        .from('chat_room_participants')
        .select('*')
        .eq('room_id', roomId)
        .eq('user_id', senderId)
        .single();

      if (participantError || !participant) {
        throw new CustomError({ code: 'UNAUTHORIZED' });
      }

      // Get sender's language preference
      const { data: senderData } = await supabase
        .from('users')
        .select('language')
        .eq('id', senderId)
        .single();

      const senderLanguage = senderData?.language || LANGUAGE.KOREAN;
      assertEnum(LANGUAGE, senderLanguage);

      // Translate message if necessary
      const translatedMessage =
        receiverLanguage === senderLanguage
          ? ''
          : await translate({
              message,
              sourceLanguage: senderLanguage,
              targetLanguage: receiverLanguage,
            });

      const now = Date.now();

      // Note: The actual message sending is now handled by Socket server
      // This endpoint is mainly for message validation and translation
      return {
        id: '', // Will be generated by Socket server
        timestamp: now,
        translatedMessage,
      } satisfies Pick<Message, 'id' | 'timestamp' | 'translatedMessage'>;
    },
  );
