import './globals.css';
import '@hyeokjaelee/pastime-ui/style.css';

import type { Metadata } from 'next';
import Image from 'next/image';

import LogoWithText from '@/assets/LogoWithText.svg';
import { LogoutButton, LayoutTab, PageContainer } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface LayoutProps {
  children: React.ReactNode;
}

const Layout = ({ children }: LayoutProps) => (
  <html lang="en">
    <PageContainer>
      <body>
        <header className="bg-black px-5 sticky top-0 flex items-center justify-between">
          <div className="flex items-center gap-5">
            <Image src={LogoWithText} alt="logo" className="h-10 w-32 my-3" />
            <LayoutTab />
          </div>
          <LogoutButton />
        </header>
        {children}
      </body>
    </PageContainer>
  </html>
);

export default Layout;
