import type { Metadata } from 'next';

import { Theme } from '@radix-ui/themes';

import { pretendard } from './_components/layout/Font';

import './globals.css';
import '@radix-ui/themes/styles.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={pretendard.variable} lang="en">
      <body className={pretendard.className}>
        <Theme>{children}</Theme>
      </body>
    </html>
  );
}
