import '../globals.css';
import '@radix-ui/themes/styles.css';

import type { Metadata } from 'next';

import { dir } from 'i18next';

import { Suspense } from 'react';

import { cn } from '@/utils/cn';

import { languages } from '../i18n/settings';

import { BottomNav } from './_components/layout/BottomNav';
import { pretendard } from './_components/layout/Font';
import { GlobalHeader } from './_components/layout/GlobalHeader';
import { GlobalProvider } from './_components/layout/GlobalProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const generateStaticParams = () => languages.map((lng) => ({ lng }));

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    lng: string;
  };
}

const RootLayout = async ({ children, params }: Readonly<RootLayoutProps>) => {
  return (
    <html
      className={cn(pretendard.variable, 'size-full')}
      dir={dir(params.lng)}
      lang={params.lng}
    >
      <body className={cn(pretendard.className, 'size-full bg-zinc-50')}>
        <GlobalProvider className="flex size-full bg-zinc-50">
          <div className="flex-1" />
          <div className="flex size-full max-w-xl flex-col overflow-x-hidden bg-white text-zinc-950">
            <GlobalHeader />
            <Suspense>{children}</Suspense>
            <BottomNav />
          </div>
          <div className="flex-1" />
        </GlobalProvider>
      </body>
    </html>
  );
};

export default RootLayout;
